# Site settings
title: Damnever's Blog
author: Damnever
header-img: img/home-bg.jpg
email: dxc.wolf@gmail.com
description: "Damnever, Damnever'd Blog, 人在 Qi 途."
baseurl: ""
url: "http://damnever.github.io"
twitter_username:  Wolfdxc
github_username:  Damnever

# Build settings
encoding: utf-8
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
permalink: /:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
comments :
  provider : duoshuo
  duoshuo :
    short_name : damnever
